### PR TITLE
Fix callback arguments order

### PR DESCRIPTION
**Pull request by fasheng**
If request failed the callback argument is always null, and looks it caused by the Inconsistent behaviour issue for `inverse_callback_arguments` option in the upstream code. I'm not sure is I missed something hope it helps.

BTW: There is no such option in my code

### CODE REVIEW

**Comment by dparlevliet** [comment]
Thanks, but this functionality is correct. It seems you're confused because you're expecting the option to reverse it from ``err, result`` to ``result, err`` but that's not the case. If you want the order to be changed to standard nodejs order then set the ``inverse_callbacks_arguments`` to true and also make sure you have the new version to do that. It was done like this for backward compatibility reasons - we would have broken too many projects implementing this change forcefully and it wasn't necessary to cause that kind of a headache.

**Comment by fasheng** [comment]
Thanks for the relay. My problem is the arguments order is not the same as expect for request success and failed, for example:

```js
client.buylimit(params, function (arg1, arg2) {
    console.log(arg1, arg2) // if success, arg1 is the result JSON object, but if failed, arg1 is null, arg2 is the JSON object instead
})
```

Hope this example could explain my viewpoint clearly.

**Comment by dparlevliet** [comment]
Correct, your description sounds like correct behavior. In the case of an error arg1 should be null and arg2 should be the error response. That response might be the bittrex error or it might be a library error, but it should still be an error. Are you saying that arg2 contains valid data? Can you provide me with the actual object response from arg2 (edit out anything sensitive of course)?

```js
client.buylimit(params, function (response, error) {
    if (error) {
       return console.error(error);
    }
    // no error
    console.log(response);
})
```

**Comment by fasheng** [comment]
Got it, I will adjust my code to dispatch the response and error correctly.

In my example, the arg2 just something like this:
```
{"success":false,"message":"INSUFFICIENT_FUNDS","result":null}                                       
{"success":false,"message":"URL request error","error":{"code":"ESOCKETTIMEDOUT","connect":false}}   
```

Thanks and close the PR now.

**Comment by dparlevliet** [comment]
No problem. I appreciate you trying to help regardless!

**Pull request closed without merging**
