### PR TITLE
Add ability to create api instances with own options

### PR DESCRIPTION
**Pull request by pldin601**
I implemented ability to create api instances with own options. Also I saved original library behavior to save backward compatibility.

Example:

```javascript
import { createInstance } from 'node-bittrex-api';

const bittrex = createInstance({
  apikey: 'key',
  apisecret: 'secret',
});

bittrex.getbalances( function( data, err ) {
  console.log( data );
});
```

### CODE REVIEW

**Comment by springjben** [comment]
import { createInstance } from 'node-bittrex-api';
^^^^^^

SyntaxError: Unexpected token import

**Comment by pldin601** [comment]
Without ES6 imports:

```javascript
const createInstance = require('node-bittrex-api').createInstance;
// or
const { createInstance } = require('node-bittrex-api');

const bittrex = createInstance({
  apikey: 'key',
  apisecret: 'secret',
});
```

**Comment by dparlevliet** [comment]
BTW, I'm not ignoring this - I just can't implement your PR as it stands because it will unnecessarily break scripts for people who don't need this feature. I'm leaving it open as a reminder for me to try implement this feature without needed to change existing scripts.

**Comment by pldin601** [comment]
@dparlevliet, I saved backward compatibility. Can you show some examples of script that could be broken?

**Comment by SagiMedina** [comment]
@pldin601 have you managed to implement this?

**Comment by pldin601** [comment]
Yes. And I'm using it in my multi-user project.

**Comment by SagiMedina** [comment]
Mind sharing?

**Comment by pldin601** [comment]
Project? No.

Why do you need to see my project?

It uses same API as original library.

```javascript
import { createInstance } from 'node-bittrex-api';

const bittrex = createInstance({
  apikey: 'key',
  apisecret: 'secret',
});

bittrex.getbalances( function( data, err ) {
  console.log( data );
});
```

**Comment by SagiMedina** [comment]
Didn't mean the project... Wich version are you using? I can't get it to work...

**Comment by pldin601** [comment]
0.7.6

**Comment by SagiMedina** [comment]
@dparlevliet Is createInstance deprecated in the last version?

**Comment by pldin601** [comment]
`createInstance` is new method from my PR, but looks like library upgraded from when I created this PR. I will merge changes ASAP.

**Comment by pldin601** [comment]
Merged.

**Pull request merged**
